make a model for room creation
dogehousetv/web pull request #100
Opened 2021-06-04 20:35 UTC by 4nkitd

![image](https://user-images.githubusercontent.com/52023083/120859868-7435f880-c5a2-11eb-9a49-def675bd42e6.png)

2021-06-04 20:36 UTC, chalkedgoose commented on src/components/rooms/Rooms.tsx
> +            <Title>New room</Title>
Can we make this into a proper arrow or function component?

2021-06-04 20:37 UTC, chalkedgoose commented on src/components/rooms/Rooms.tsx
> +                    </div>) : (roomForm)}
Should be called like <RoomForm/>

2021-06-05 15:45 UTC, lucemans approved these changes

2021-06-05 15:47 UTC, chalkedgoose requested changes

2021-06-05 15:47 UTC, chalkedgoose commented on src/components/rooms/Rooms.tsx
> +                    </Row>) : (roomForm())}
Change to Proper JSX Element

2021-06-05 16:26 UTC, chalkedgoose commented on src/components/rooms/Rooms.tsx
> +                    </Row>) : (roomForm())}
<RoomForm/>

2021-06-05 16:26 UTC, chalkedgoose commented on src/components/rooms/Rooms.tsx
> +                    </Row>) : (roomForm())}
<RoomForm/>

2021-06-05 16:38 UTC, chalkedgoose approved these changes

2021-06-05 16:38 UTC, chalkedgoose commented on src/components/rooms/Rooms.tsx
> +                    </Row>) : (roomForm())}
`
<RoomForm/>
`

2021-06-05 17:01 UTC, merged