replaced all inputs with our component
dogehousetv/web pull request #123
Opened 2021-06-11 17:50 UTC by joelimgu

Don't look at the first two commits, it's just me doing stupid things

2021-06-11 19:22 UTC, lucemans requested changes
Please change this and then LGTM

2021-06-11 19:22 UTC, lucemans commented on src/components/inputs/input.tsx
> +background: transparent;
Indentation

2021-06-11 19:22 UTC, lucemans commented on src/components/inputs/input.tsx
> +}
Indentation

2021-06-11 19:22 UTC, lucemans commented on src/components/rooms/Rooms.tsx
> +
Ahhhhhhhhhhhh

2021-06-11 21:57 UTC, joelimgu reviewed
yep that's better

2021-06-12 00:07 UTC, chalkedgoose commented on src/components/search/Search.tsx
> +                <SearchInput placeholder="Search for rooms, users or categories" onChange={(event) => {setSearchResults(event.target.value);}}/>
Nit: A anonymous function without curly braces would work fine here.

2021-06-12 23:14 UTC, chalkedgoose approved these changes

2021-06-13 08:32 UTC, 4nkitd approved these changes
LGTM!

2021-06-13 12:08 UTC, joelimgu reviewed
ok

2021-06-13 16:30 UTC, lucemans commented
The changes that were requested were never made, @joelimgu please have another look at this.

2021-06-16 16:17 UTC, lucemans approved these changes
LGTM!

2021-06-16 16:17 UTC, merged