Logo component - better drag experience
dogehousetv/web pull request #57
Opened 2021-06-01 21:14 UTC by KristofKekesi

Better drag experience to the logo component. It's not that elegant but better when dragging it to a new tab.
![image](https://user-images.githubusercontent.com/64812024/120391335-2796b700-c32f-11eb-9e66-37015b3d4004.png)

2021-06-01 22:58 UTC, chalkedgoose requested changes

2021-06-01 22:58 UTC, chalkedgoose commented on src/components/logo/Logo.tsx
> +        <a href="/dashboard">
Nice commit! Is there any chance you could swap out this plain HTML anchor
tag with a [next link](https://nextjs.org/docs/api-reference/next/link)?

2021-06-01 22:58 UTC, chalkedgoose commented on src/components/logo/Logo.tsx
> +        <a href="/dashboard">
Looks find and dandy to me just that one change and it should be good to go.

2021-06-01 23:10 UTC, chalkedgoose commented on src/components/logo/Logo.tsx
> +        <a href="/dashboard">
Also as a side not @KristofKekesi the /dashboard route is now at /dash

2021-06-02 13:55 UTC, KristofKekesi commented
I had to put a blank a tag inside the next link becouse just the next link didn't do the drag effect.

2021-06-02 17:03 UTC, chalkedgoose approved these changes
LGTM

2021-06-02 17:07 UTC, merged